# SPDX-FileCopyrightText: The Threadbare Authors
# SPDX-License-Identifier: CC0-1.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    args:
      - --enforce-all
  - id: check-case-conflict
  - id: check-illegal-windows-names
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: \.svg$
  - id: trailing-whitespace
    exclude: \.svg$

- repo: https://github.com/editorconfig-checker/editorconfig-checker
  rev: v3.4.0
  hooks:
  - id: editorconfig-checker

- repo: https://github.com/Scony/godot-gdscript-toolkit
  rev: 4.3.4
  hooks:
  - id: gdformat
  - id: gdlint
    exclude: script_templates/
exclude: |
  (?x)^(
    addons/dialogue_manager/(.*)|
    addons/git_describe/(.*)
  )$
