version = 1

# .uid files are machine-generated and must be checked in but do not involve any
# creative work.
[[annotations]]
path = [
    "scenes/**/*.uid",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Godot resource files are creative works, but cannot contain copyright or
# license headers. Comments are supported, but will be discarded by the editor
# when saving changes to these files.
[[annotations]]
path = [
    "scenes/*.tscn",
    "scenes/**/*.tscn",
    "scenes/**/*.tres",
    # .import files are largely machine-generated but developers can tweak their contents
    "**/*.import",
]
SPDX-FileCopyrightText = "The Threadbare Authors"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = "addons/dialogue_manager/**"
SPDX-FileCopyrightText = "2022-present Nathan Hoad and Dialogue Manager contributors."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "assets/xylophone-sampler-pack/*.ogg"
SPDX-FileCopyrightText = "2013 juancamiloorjuela"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "assets/tiny-swords/**/*.png",
    "assets/tiny-swords/**/*.aseprite",
]
SPDX-FileCopyrightText = "Pixel Frog"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "assets/collectibles/*.png",
    "assets/intro/*.png",
    "assets/logo/*.png",
    "assets/towers/*.png",
]
SPDX-FileCopyrightText = "The Threadbare Authors"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "assets/inputs/keyboard-and-mouse/Blanks/*.png",
    "assets/inputs/keyboard-and-mouse/Dark/*.png",
    "assets/inputs/keyboard-and-mouse/Light/*.png",
]
SPDX-FileCopyrightText = "Nicolae (XELU) Berbece"
SPDX-License-Identifier = "CC0-1.0"
