# SPDX-FileCopyrightText: The Threadbare Authors
# SPDX-License-Identifier: MPL-2.0
name: Discord Notification

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  notify:
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      if: github.event.pull_request.merged == true
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MERGE }}
        # DISCORD_USERNAME: # Omitted in favor of Discord default ("GitHub")
        # DISCORD_AVATAR: # Omitted in favor of Discord default (GitHub logo)
      uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554 # 0.4.0
